#!/usr/bin/env perl

use strict;
use warnings;

use FindBin qw($Bin);
use File::Spec;

use lib File::Spec->catdir( $Bin, '..', '..', '..', 'lib' );

use Git::Smart::Folder ();

my $exit = eval { Git::Smart::Folder::main(@ARGV) };

if ( my $error = $@ ) {
    chomp $error;
    print STDERR $error . "\n";
    exit 1;
}

exit $exit;
